# Week 5 & 6 Coding Assignment

DSC 530

Rosie Navarro

July 16, 2026

In [50]:
import pandas as pd
import numpy as np

# Chapter 4: 

## Exercise 1:

With the earthquake.csv file, select all the earthquakes in Japan with a magnitude of 4.9 or greated using the mb magnitude type. 

The first step I will take for this problem is loading the data, making sure that the correct one is being used and is loaded properly. The following shows the first 50 rows of the data.

In [51]:
earthquake = pd.read_csv("/Users/rosienavarro/Data_Science/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_04/exercises/earthquakes.csv")
earthquake.head(50)

,mag,magType,time,place,tsunami,parsed_place
0,1.35,ml,1539475168010,"9km NE of Aguanga, CA",0,California
1,1.29,ml,1539475129610,"9km NE of Aguanga, CA",0,California
2,3.42,ml,1539475062610,"8km NE of Aguanga, CA",0,California
3,0.44,ml,1539474978070,"9km NE of Aguanga, CA",0,California
4,2.16,md,1539474716050,"10km NW of Avenal, CA",0,California
5,2.61,md,1539473686440,"55km ESE of Punta Cana, Dominican Republic",0,Dominican Republic
6,1.70,ml,1539473176017,"105km W of Talkeetna, Alaska",0,Alaska
7,1.13,md,1539473060280,"10km NW of Parkfield, CA",0,California
8,0.92,md,1539473042310,"6km NW of The Geysers, CA",0,California
9,4.70,mb,1539472814760,"219km SSE of Saparua, Indonesia",0,Indonesia
10,0.50,ml,1539471831030,"10km NE of Aguanga, CA",0,California
11,2.77,md,1539471621260,"53km SE of Punta Cana, Dominican Republic",0,Dominican Republic
12,0.50,ml,1539470934710,"9km NE of Aguanga, CA",0,California
13,4.50,mb,1539470898340,"120km SSW of Banda Aceh, Indonesia",0,Indonesia
14,2.13,md,1539470851950,"14km NW of Parkfield, CA",0,California
15,2.00,ml,1539470304219,"156km WNW of Haines Junction, Canada",0,Canada
16,0.72,md,1539470237230,"2km N of The Geysers, CA",0,California
17,1.69,md,1539468879730,"2km S of Maricao, Puerto Rico",0,Puerto Rico
18,2.00,ml,1539468687232,"57km SSW of Kaktovik, Alaska",0,Alaska
19,0.92,ml,1539468671340,"4km ENE of Calimesa, CA",0,California
20,2.82,md,1539467908560,"61km N of Tierras Nuevas Poniente, Puerto Rico",0,Puerto Rico
21,1.70,ml,1539467905609,"64km SSW of Salcha, Alaska",0,Alaska
22,0.81,ml,1539467508540,"4km NW of San Clemente, CA",0,California
23,0.55,ml,1539466580200,"27km E of Coso Junction, CA",0,California
24,0.67,ml,1539466409430,"6km SSE of Idyllwild, CA",0,California
25,2.10,md,1539466356170,"14km NW of Parkfield, CA",0,California
26,2.80,ml,1539466288954,"111km NNW of Arctic Village, Alaska",0,Alaska
27,1.10,ml,1539465520462,"43km S of Redoubt Volcano, Alaska",0,Alaska
28,1.80,ml,1539464607849,"86km SW of Anchor Point, Alaska",0,Alaska
29,0.93,md,1539464503490,"15km NW of Parkfield, CA",0,California
30,1.52,ml,1539463322040,"2km WNW of Manhattan, Montana",0,Montana
31,2.30,ml,1539462724148,"79km SW of Kaktovik, Alaska",0,Alaska
32,1.30,ml,1539461038285,"13km E of Hawthorne, Nevada",0,Nevada
33,1.70,ml,1539460963493,"45km S of Kaktovik, Alaska",0,Alaska
34,2.20,ml,1539460430189,"83km W of Anchor Point, Alaska",0,Alaska
35,1.90,ml,1539460155900,"60km S of Cantwell, Alaska",0,Alaska
36,5.00,mww,1539459504090,"165km NNW of Flying Fish Cove, Christmas Island",1,Christmas Island
37,1.60,ml,1539459197502,"95km N of College, Alaska",0,Alaska
38,2.12,ml,1539458974490,"7km SW of Volcano, Hawaii",0,Hawaii
39,-0.10,ml,1539458844506,"6km NW of Lemmon Valley, Nevada",0,Nevada
40,1.31,ml,1539458726910,"10km ESE of Lincoln, Montana",0,Montana
41,0.20,ml,1539458665088,"6km NW of Lemmon Valley, Nevada",0,Nevada
42,0.86,ml,1539457997460,"12km N of Borrego Springs, CA",0,California
43,2.92,md,1539457653730,"67km NNE of Arecibo, Puerto Rico",0,Puerto Rico
44,0.32,ml,1539457563160,"10km NE of Aguanga, CA",0,California
45,1.84,md,1539457145410,"23km SSW of South Dos Palos, CA",0,California
46,1.90,ml,1539457095255,"13km W of Y, Alaska",0,Alaska
47,1.14,md,1539455748700,"6km NNW of Pinnacles, CA",0,California
48,0.90,ml,1539455306730,"42km WSW of Tonopah, Nevada",0,Nevada
49,-0.10,ml,1539455017464,"6km NW of Lemmon Valley, Nevada",0,Nevada

Our goal is to find the earthquakes in Japan that had a magnitude of 4.9 or greater, this can be done through filtering, looking at data that follows the question criteria. There are only 4 rows that meet the criteria.

In [52]:
japan = earthquake[(earthquake["parsed_place"].str.contains("Japan"))&
    (earthquake["mag"] >= 4.9) &
    (earthquake["magType"] == "mb")]

japan

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

## Exercise 2: 

Create bins for each full number of earthquake magnitude (for instance, the first bin is (0,1], the second is (1,2], and so on) with the ml magnitude type and count how many are in each bin.

First step for this exercise is to create groups for the intervals. The intervals will be 0-1, 1-2, 2-3, etc. until the max ml is reached. Bin_count is used to count the number of values that correspond to each bin.

In [53]:
ml_quakes = earthquake[earthquake["magType"] == "ml"] # filter for only ml values

bins = np.arange(0, ml_quakes["mag"].max() + 1, 1)

# groups the values into intervals 
mag_bins = pd.cut(ml_quakes["mag"], bins=bins) # cut is used to assign each earthquake to a magnitude range

# counts the number of earthquakses that are in each interval. 
bin_count = mag_bins.value_counts().sort_index()

bin_count

mag
(0.0, 1.0]    2207
(1.0, 2.0]    3105
(2.0, 3.0]     862
(3.0, 4.0]     122
(4.0, 5.0]       2
(5.0, 6.0]       1
Name: count, dtype: int64

The max ml value was 6, 6 different bins were created. The bin with the most was 1-2, the one with the least was 5-6. If a histogram were created for this problem, the data would skewed be skewed to the right.

## Exercise 4: 

Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magnitude type along the columns.

A crosstab is created to examine the relationship between tsunami and magnitude types (earthquakes). Instead of frequency, max value for each magnitude type was found (aggregation max)

In [54]:
cross_tab = pd.crosstab(
    earthquake["tsunami"], 
    earthquake["magType"], 
    values = earthquake["mag"], 
    aggfunc = "max")

cross_tab

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

Each cell contains the largest earthquake magnitude which is done using the values and through aggregation. The magnitude type is shown as the columns and the comparison can be seen if there was or wasn't a tsunami (0 or 1). Larger magnitude is usually associated with a tsumani, but this is only one factor that is involved.

## Exercise 6: 

Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

To find the average of the trade data, data aggregation is done using mean. OHLC are the column names (high, low, close, open, and volume). First step is to make sure that the data loads and the correct columns are being used to answer the question.

In [55]:
# loading faang.csv file
faang = pd.read_csv("/Users/rosienavarro/Data_Science/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_04/exercises/faang.csv")

faang

,ticker,date,high,low,open,close,volume
0,FB,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900.0
1,FB,2018-01-03,184.779999,181.330002,181.880005,184.669998,16886600.0
2,FB,2018-01-04,186.210007,184.100006,184.899994,184.330002,13880900.0
3,FB,2018-01-05,186.899994,184.929993,185.589996,186.850006,13574500.0
4,FB,2018-01-08,188.899994,186.330002,187.199997,188.279999,17994700.0
...,...,...,...,...,...,...,...
1250,GOOG,2018-12-24,1003.539978,970.109985,973.900024,976.219971,1590300.0
1251,GOOG,2018-12-26,1040.000000,983.000000,989.010010,1039.459961,2373300.0
1252,GOOG,2018-12-27,1043.890015,997.000000,1017.150024,1043.880005,2109800.0
1253,GOOG,2018-12-28,1055.560059,1033.099976,1049.619995,1037.079956,1414800.0
1254,GOOG,2018-12-31,1052.699951,1023.590027,1050.959961,1035.609985,1493300.0

The following Pivot table shows the averages for all the tickers during their open, close, low, high, and volume. This helps us identify how the companies behaves right when they open, during, and at the end. It also provides information about how much they change (high, low) and which companies are performing better. Just by loading the data it can be overwhelming to see what is happening in the data.

In [56]:
pivot = pd.pivot_table(
    faang, 
    index = "ticker", 
    values = ["open", "high", "low", "close", "volume"], 
    aggfunc = "mean")

pivot

              close         high          low         open        volume
ticker
AAPL      47.263357    47.748526    46.795877    47.277859  1.360803e+08
AMZN    1641.726176  1662.839839  1619.840519  1644.072709  5.648994e+06
FB       171.510956   173.613347   169.303148   171.472948  2.765860e+07
GOOG    1113.225134  1125.777606  1101.001658  1113.554101  1.741965e+06
NFLX     319.290319   325.219322   313.187330   319.620558  1.146962e+07

## Exercise 7: 

Calculate the z-scores for each numeric column of Amazon’s data (ticker is AMZN) in Q4 2018 using apply().

Question is only asking for dates in Q4, those would be between November 1st to the end of December. Filter can be created to only see Amazon data during those dates. Since z-score is being used, numeric data from the data set is only going to be used, date and ticker would no longer be relavent. Z-score can then be applied to all of numeric values, using equation.

In [57]:
faang["date"] = pd.to_datetime(faang["date"])

amzn_q4 = faang[
    (faang["ticker"] == "AMZN") &
    (faang["date"] >= "2018-10-01") &
    (faang["date"] <= "2018-12-31")]

# numeric values are the only ones being selected/relavent
num_col = amzn_q4.select_dtypes(include = np.number) 

z_score = num_col.apply(
    lambda x: (x - x.mean())/ x.std()) # z-score equation

z_score

         high       low      open     close    volume
690  2.368006  2.502113  2.337813  2.385848 -1.630411
691  2.227302  2.247433  2.190795  2.155037 -0.861879
692  2.058955  2.139987  2.068570  2.025489 -0.920345
693  1.819474  1.781561  1.850048  1.722816 -0.126582
694  1.628173  1.554416  1.642819  1.584748 -0.298771
..        ...       ...       ...       ...       ...
748 -2.159820 -2.187566 -2.179582 -2.226185 -0.141238
749 -1.611714 -1.810493 -2.026617 -1.339674  1.123063
750 -1.641276 -1.626703 -1.456521 -1.404343  0.849827
751 -1.325261 -1.231588 -1.328549 -1.289951  0.496102
752 -1.273456 -0.975763 -1.078283 -1.122691 -0.246405

[63 rows x 5 columns]

## Exercise 10: 

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. Complete the following tasks to practice the skills you've learned up to this point in the book:



Prepare the data
Read in the data in the covid19_cases.csv file.
Create a date column by parsing the dateRep column into a datetime.
Set the date column as the index.
Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.
Sort the index.

The following opens the covid_19 data.

In [58]:
covid_data = pd.read_csv("/Users/rosienavarro/Data_Science/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_04/exercises/covid19_cases.csv")

covid_data

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159
...,...,...,...,...,...,...,...,...,...,...,...,...
43713,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
43714,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
43715,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
43716,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
43717,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN

Parsed dataRep converted to datetime. Datetime convers the text into date values.

In [59]:
covid_data["date"] = pd.to_datetime(
    covid_data["dateRep"], 
    format = "%d/%m/%Y")

# sets date as index
covid_data = covid_data.set_index("date")

The following converts/replaces United states and United Kingdom to their abbreviations.

In [60]:
covid_data["countriesAndTerritories"] = covid_data[
    "countriesAndTerritories"].replace({
        "United_States_of_America" : "USA", 
        "United_Kingdom" : "UK"})

The following sorts the index. To make sure the following steps worked, chart is displayed again.

In [61]:
covid_data = covid_data.sort_index()
covid_data

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,Belgium,BE,BEL,11455519.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Mexico,MX,MEX,127575529.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Ecuador,EC,ECU,17373657.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Russia,RU,RUS,145872260.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-19,19/09/2020,19,9,2020,77,0,Guinea,GN,GIN,12771246.0,Africa,5.105218
2020-09-19,19/09/2020,19,9,2020,1771,62,Turkey,TR,TUR,82003882.0,Asia,28.358414
2020-09-19,19/09/2020,19,9,2020,28,0,Guinea_Bissau,GW,GNB,1920917.0,Africa,3.019391
2020-09-19,19/09/2020,19,9,2020,0,0,Tunisia,TN,TUN,11694721.0,Africa,35.708419
2020-09-19,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645

### For the five countries with the most cases (cumulative), find the day with the largest number of cases.

There are two things done for this problem, country and cases are grouped. Then the sum of the top five are displayed. Look for the countries with the most cases.

In [62]:
top_5 = covid_data\
    .groupby('countriesAndTerritories').cases.sum()\
    .nlargest(5).index

top_5

covid_data[covid_data.countriesAndTerritories.isin(top_5)]\
    .groupby('countriesAndTerritories').cases.idxmax()

countriesAndTerritories
Brazil   2020-07-30
India    2020-09-17
Peru     2020-08-17
Russia   2020-07-18
USA      2020-07-25
Name: cases, dtype: datetime64[us]

The following shows the contries with the most cumulative cases and the dates they had the most cases.

### Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.

The final 7 days are slected for the top 5 countries with the most cases.

In [63]:
top_5_data = covid_data[
    covid_data["countriesAndTerritories"].isin(top_5)]

average_day = (
    top_5_data.groupby("countriesAndTerritories")["cases"]
    .rolling(7)
    .mean()
    .reset_index())

last_week = average_day.groupby(
    "countriesAndTerritories").tail(7)

last_week

     countriesAndTerritories       date         cases
257                   Brazil 2020-09-13  27526.714286
258                   Brazil 2020-09-14  27562.000000
259                   Brazil 2020-09-15  28259.428571
260                   Brazil 2020-09-16  31455.714286
261                   Brazil 2020-09-17  31599.142857
262                   Brazil 2020-09-18  30991.428571
263                   Brazil 2020-09-19  30431.285714
520                    India 2020-09-13  91506.428571
521                    India 2020-09-14  91687.714286
522                    India 2020-09-15  92830.571429
523                    India 2020-09-16  92890.142857
524                    India 2020-09-17  93198.571429
525                    India 2020-09-18  93180.428571
526                    India 2020-09-19  92575.714286
716                     Peru 2020-09-13   5590.000000
717                     Peru 2020-09-14   5663.142857
718                     Peru 2020-09-15   6040.714286
719                     Peru 2020-09-16   5975.714286
720                     Peru 2020-09-17   5946.285714
721                     Peru 2020-09-18   5718.714286
722                     Peru 2020-09-19   5677.428571
980                   Russia 2020-09-13   5293.142857
981                   Russia 2020-09-14   5329.428571
982                   Russia 2020-09-15   5375.714286
983                   Russia 2020-09-16   5437.142857
984                   Russia 2020-09-17   6247.142857
985                   Russia 2020-09-18   5558.714286
986                   Russia 2020-09-19   5616.000000
1244                     USA 2020-09-13  34320.285714
1245                     USA 2020-09-14  34794.000000
1246                     USA 2020-09-15  36307.000000
1247                     USA 2020-09-16  39785.714286
1248                     USA 2020-09-17  38738.714286
1249                     USA 2020-09-18  39604.428571
1250                     USA 2020-09-19  39911.285714

### Find the first date that each country other than China had cases.

Goal of this problem is to find the date when the first case appear in each country. This can be done by grouping countries with cases that are more than 0.

In [64]:
first_case = (
    covid_data[
        (covid_data["cases"] > 0) &
        (covid_data["countriesAndTerritories"] != "China")]
    .groupby("countriesAndTerritories")
    .apply(lambda x: x.index.min()))

first_case

countriesAndTerritories
Afghanistan      2020-02-25
Albania          2020-03-09
Algeria          2020-02-26
Andorra          2020-03-03
Angola           2020-03-22
                    ...
Vietnam          2020-01-24
Western_Sahara   2020-04-26
Yemen            2020-04-10
Zambia           2020-03-19
Zimbabwe         2020-03-21
Length: 209, dtype: datetime64[us]

### Rank the countries by cumulative cases using percentiles.
Countries with values closer to 1 have higher cumulative case counts compared to the other countries.

In [65]:
country_total = (
    covid_data.groupby("countriesAndTerritories")["cases"]
    .sum())

percentile = country_total.rank(pct = True) # pct converts the rank between 0-1. 
percentile.sort_values(ascending = False)

countriesAndTerritories
USA                            1.000000
India                          0.995238
Brazil                         0.990476
Russia                         0.985714
Peru                           0.980952
                                 ...
Greenland                      0.023810
Montserrat                     0.016667
Falkland_Islands_(Malvinas)    0.016667
Holy_See                       0.009524
Anguilla                       0.004762
Name: cases, Length: 210, dtype: float64

The US has the highest percentile and Anguilla has the lowest percentile of covid cases (0.0047).